all: echo pwd mv cmp cat ls

echo: echo.c
	gcc -o echo echo.c

pwd: pwd.c
	gcc -o pwd pwd.c

mv: mv.c
	gcc -o mv mv.c

cmp: cmp.c
	gcc -o cmp cmp.c

cat: cat.c
	gcc -o cat cat.c

ls: ls.c
	gcc -o ls ls.c

clean:
	rm -f echo pwd mv cmp cat ls
